export const categoryGames = [
  {
    categoryId: "pitching",
    games: [
      {
        date: "1986/04/29",
        homeTeam: "Boston Red Sox",
        visitingTeam: "Seattle Mariners",
        id: "BOS198604290",
        gameDescription: "Roger Clemens records 20 strikeouts for Boston",
        location: "Fenway Park",
        homeScore: 3,
        visitingScore: 1,
        matchup: "SEA-BOS",
      },
      {
        date: "1996/09/18",
        homeTeam: "Detroit Tigers",
        visitingTeam: "Boston Red Sox",
        id: "DET199609180",
        gameDescription:
          "Roger Clemens records 20 strikeouts for Boston (again)",
        location: "Tiger Stadium",
        homeScore: 0,
        visitingScore: 4,
        matchup: "BOS-DET",
      },
      {
        date: "1998/05/06",
        homeTeam: "Chicago Cubs",
        visitingTeam: "Houston Astros",
        id: "CHN199805060",
        gameDescription: "Kerry Wood records 20 strikeouts for Chicago",
        location: "Wrigley Field",
        homeScore: 2,
        visitingScore: 0,
        matchup: "HOU-CHC",
      },
      {
        date: "2016/05/11",
        homeTeam: "Washington Nationals",
        visitingTeam: "Detroit Tigers",
        id: "WAS201605110",
        gameDescription: "Max Scherzer records 20 strikeouts for Washington",
        location: "Nationals Park",
        homeScore: 3,
        visitingScore: 2,
        matchup: "DET-WAS",
      },
      {
        date: "1970/04/22",
        homeTeam: "New York Mets",
        visitingTeam: "San Diego Padres",
        id: "NYN197004220",
        gameDescription:
          "Tom Seaver records 10 strikeouts in a row for the Mets",
        location: "Shea Stadium",
        homeScore: 2,
        visitingScore: 1,
        matchup: "SD-NYM",
      },
      {
        date: "1968/10/02",
        homeTeam: "St. Louis Cardinals",
        visitingTeam: "Detroit Tigers",
        id: "SLN196810020",
        gameDescription:
          "Bob Gibson records a record 17 strikeouts in a World Series game",
        location: "Busch Stadium",
        homeScore: 4,
        visitingScore: 0,
        matchup: "DET-STL",
      },
      {
        date: "1970/06/12",
        homeTeam: "San Diego Padres",
        visitingTeam: "Pittsburgh Pirates",
        id: "SDN197006121",
        gameDescription:
          "Dock Ellis throws a no-hitter under the influence of LSD",
        location: "San Diego Stadium",
        homeScore: 0,
        visitingScore: 2,
        matchup: "PIT-SD",
      },
    ],
  },
];
